# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2667a10db3cbaae6d5b8131bf5b4738151cf6f1b7a6e7f0e524fbf8d9a7a0a721d6acdc0bce8ef8a9db220952d6a7dca3d7d83c13cb7183df5c9482438b5fcb

test:
  secret_key_base: bfb0c7010e0021b46dd85e55d4492436a9683fcbb855aeb8e5caea62b44f080c3b7d8bbbcc9fd73cf6a714121763df027c21d64b490ade262183f438ba5cc294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
